_target_: src.models.nets.chainhoi.ChainHOI
layout: hml3d_graph_1
joint_dim: 12
text_feat_dim: 512
time_embed_dim: 256
obj_clound_dim: 256
model_dim: 64
trans_layers: 6
trans_layers2: 4
num_layers: 6
base_dim: 64
up_layers: "2,4"
gp_norm: 4
pos_emb: cos
arch: 1
block_arch: 1
temp_arch: cross
input_proj_type: 0
reduce_joint: avg
has_obj: False
down_sample: 8
res: True
nheads: 4
joint_arch: "sa"
rpe: True
post_proj: True
obj_type: "add"
cond_type: "add"
two_token: False
connect_all: False