_target_: src.models.nets.kfg.KFG1_df
motion_dim: ${data.motion_dim}
model_dim: 512
text_feat_dim: 512
num_heads: 8
dim_feedforward: 2048
dropout: 0.1
num_layers: 4
arch: 1
head_type: 1
head_drop: 0
text_type: 1
pose_only: true
